repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--verbose"]
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      #- id: no-commit-to-branch
      #  args: ['--branch', 'master', '--pattern', '^(?!((hotfix|feature|bug)-[a-zA-Z-]{1,4}-[0-9]{1,4})).*']
